# Generated by Django 4.2.4 on 2023-08-13 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_options_product_dateadded'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isfeatured',
            field=models.BooleanField(default=False),
        ),
    ]
